@startuml
'https://plantuml.com/class-diagram

class NavController
class NavHostController

class NavHostFragment{
private NavHostController mNavController


public NavController getNavController()
}
interface NavHost{
public NavController getNavController()
}

NavHostFragment --|> Fragment
NavHostFragment ..|> NavHost

NavHostController --|> NavController

@enduml